// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ChangeForiegnKeyFromUser_IDToEmployeeIDINREntalsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeForiegnKeyFromUser_IDToEmployeeIDINREntalsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202003071546443_ChangeForiegnKeyFromUser_IDToEmployeeIDINREntalsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
