USE [master]
GO

/****** Object:  Database [Vidly]    Script Date: 4/30/2020 12:59:45 AM ******/
CREATE DATABASE [Vidly]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Vidly', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DAFRO\MSSQL\DATA\Vidly.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Vidly_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DAFRO\MSSQL\DATA\Vidly_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Vidly].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Vidly] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Vidly] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Vidly] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Vidly] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Vidly] SET ARITHABORT OFF 
GO

ALTER DATABASE [Vidly] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Vidly] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Vidly] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Vidly] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Vidly] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Vidly] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Vidly] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Vidly] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Vidly] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Vidly] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Vidly] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Vidly] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Vidly] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Vidly] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Vidly] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Vidly] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Vidly] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Vidly] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Vidly] SET  MULTI_USER 
GO

ALTER DATABASE [Vidly] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Vidly] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Vidly] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Vidly] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Vidly] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Vidly] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Vidly] SET  READ_WRITE 
GO

